spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: false
  freemarker:
    cache: false
  jwt:
    secret: govlepel@$&
  redis:
    host: localhost
    port: 6379
  kafka:
    consumer:
      grouping:
        id: my-group
      topic: chat-topic